diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.426  # URDF와 일치시킴
    wheel_radius: 0.0575

    base_frame_id: base_link
    odom_frame_id: odom
    use_stamped_vel: false
    publish_rate: 50.0
    open_loop: false

    cmd_vel_timeout: 0.25
    enable_odom_tf: false
